### ISSUE TITLE
unable to replace assetspath in js, but success in html, using webpack4

### ISSUE THREAD

**Issue by peade** [Va1/string-replace-loader#43] opened 2018-04-17 07:03 UTC
I use string-replace-loader to replace assetspath both in html and js.
It works in html, but fails in js.
this is my code:
`{
                    loader: 'string-replace-loader',
                    options: {
                        search: '"\/images\/',
                        replace: '"' + config.publicPath + 'images/',
                        flags: 'ig'
                    }
                }`

**Comment by Va1** [comment] 2020-04-08 16:10
sorry for such a delay. it may be caused by how webpack injects paths. i would advice you to debug by checking the contents of the subject files in the moment of replacement – it's possible that they're not there at that moment. otherwise, if it is not an issue anymore (after almost 2 years lol), close it. thanks

**Comment by AllanJard** [comment] 2021-06-16 14:29
I know this is an old one now, but I'm hitting the same issue and think I know what is causing it, but not how to resolve it. The loader is operating on the entry point only - but I need the string replacement to happen on the files that get resolved as a result of the entry point. I'd guess the original issue was because of the same thing.

**Comment by AllanJard** [comment] 2021-06-16 14:30
Looks like the answer is in #54. Use a plug-in.

**Comment by Va1** [comment] 2021-06-27 17:19
thanks for your answer @AllanJard . the tricky part with projects like this is in that Webpack setups are very different in different projects and it is therefore usually quite hard to debug and find a solution. what i'm trying to provide with the loader is that it works in the expected & consistent way when it's used in a clean & simple, isolated Webpack setup, as automated tests verify. even though i'm happy to have a look into the issue and answer questions, everything beyond is up to a user.

i believe, this one can be now closed as well, then.

**Closed by Va1** 2021-06-27 17:19 UTC
